@url = https://localhost:5001
@router = api/account
@authToken = {{login.response.body.jwt}}
@refreshToken = {{refreshUserToken.response.body.jwt}}

###

# @name register
POST {{url}}/{{router}}/register
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "email": "test6@gmail.com",
    "password": "123456"
}

###

# @name login
POST {{url}}/{{router}}/login
Content-Type: application/json

{
    "username": "user@gmail.com",
    "password": "123456"
}

###

# @name refreshUserToken

GET {{url}}/{{router}}/refresh-user-token
Authorization: Bearer {{authToken}}


###

# @name confirmEmail
PUT {{url}}/{{router}}/confirm-email
Content-Type: application/json

{
    "email": "nhokpio95@gmail.com",
    "token": "Q2ZESjhNZnZ5MkRhbzNwRnNnNVQ4aTk5WUhRLzJmOVFtS3pYd0Fhb2c0aUgwaU9hNzlMRitDeUxPekNrL205dVIwUEFCdEp2ZVZ5cEdSN0tUN2Y5TTE1ZDZjdTRUQzhMbXZyUWR2anJrRkoraGUwRlM2dzUzakdhdzNjVndVSzlta0wxZDlZbHhnbDd5ZVkvL1NOZUFrYnhRNzVLWGZvbkVadU5aZFhIbVR6NUZXOVpPMzE0MTZaTlNNL2pUQTcxMUVqRUlFajAvSVM1dzRYb3Y3bEEzQ25yKytNOW1tTEpzcHRyamR3QktZeVVJcEczUjBYbG1LRzdWRjd4OENRQi9XTHV5QT09"
}

###

# @name resendEmailConfirmation
@emailResendConfirm=nhokpio95@gmail.com
POST {{url}}/{{router}}/resend-email-confirmation-link/{{emailResendConfirm}}

###

# @name forgotPassword
@emailForgotPassword=nhokpio95@gmail.com
POST {{url}}/{{router}}/forgot-password/{{emailForgotPassword}}

###

# @name resetPassword
PUT {{url}}/{{router}}/reset-password
Content-Type: application/json

{
    "email": "nhokpio95@gmail.com",
    "token": "Q2ZESjhNZnZ5MkRhbzNwRnNnNVQ4aTk5WUhUckpHNzVUUmExN1NDVmovR1BqdzdqUmVOam9QZWh3VXc4OUVhRnNXSmhBZGtxMVhpRUdFc3hPTmIzMWsvcEdmWWpaUHBERTlTako3a3BxaENxSkl0cXllbWkvbUJITnJkb2FuaDN1QjQ1Qzl6YzdkeTF2bnlRaWpqbmtLc0orQWUrejVzMGhaSHV3RWl5c1VwSnJQRHVKUTFMU2FqVVh1R2lEYVdxV2JhaEk4bUFsQjI4WUdCL0t4WXQ2OEpqN2lnSFVzcmJackRUdGxWejdzRzU5dzg0",
    "newPassword": "321321"
}

###

# @name registerValidation
POST {{url}}/{{router}}/register
Content-Type: application/json

{
    "firstName": "JohnJohnJohnJohnJohnJohnJohnJohnJohn",
    "lastName": "DoeDoeDoeDoeDoeDoeDoeDoeDoeDoeDoe",
    "email": "johnDoe@gmail.com",
    "password": "123456"
}