@url = https://graph.facebook.com


###

# @name verify-facebook-token
@input_token=EAAd9NmiO3IsBO5AVor9K84L40d1ADysZCFSjTQ6CYERcxvaeMDXNnVZAGhn0m4n6hPse6QKRV4dvcVCEtzpnESOni37ZC68k2BG7SBCmIDlrSbh3ddtxQKZBHjnchgdD4EI5ZBbCBqma3l8eYWQpc1mFe9ZAVU83B1mzqPT2r6rO94QfOmbvFTSXZBhjGQMAOJp7995ZA7foTpDk3ZCvm0hm0jpBVWrFGqi6D2QZDZD
@access_token=2107997472873611|b988ab299f5052fe061d68626f740c96

GET {{url}}/debug_token?input_token={{input_token}}&access_token={{access_token}}



###
