@url = https://localhost:5001
@router = api/booking

### 


# @name getListOfBookingSchedule
GET {{url}}/{{router}}/schedule?
  # &searchTerm= "A-2-4"
  # &sort=nameDesc
  &DepartureStationId=1
  &ArrivalStationId=3
  &DepartureTime=2024-01-21T03:14:39.909Z
  # &ArivalTime = 2024-01-18 16:18:28.0000000
  &RoundTrip=true


### 

# @name getScheduleById
@id = 2

GET {{url}}/{{router}}/schedule/{{id}}

### 

# @name getTrainDetailsByScheduleId
@id = 1

GET {{url}}/{{router}}/train/{{id}}


### 

# @name getCarriageTypes
@id = 2
GET {{url}}/{{router}}/carriageTypes/{{id}}