@url = https://localhost:5001

### 

# @name addCarriage
POST {{url}}/api/carriages
Content-Type: application/json

{
  "Name" : "Test",
  "TrainId" : "1",
  "NumberOfCompartment" : 1,
  "ServiceCharge" : 2.5,
  "Status" : "Test"
}


### 

# @name getListOfCarriage
GET {{url}}/api/carriages?
  &pageNumber=1
  &pageSize=5
  # &searchTerm=New Train
  # &sort=nameDesc
  # &trainCompanyId=2


### 

# @name getCarriagenById
@id = 1

GET {{url}}/api/carriages/{{id}}


### 

# @name UpdateCarriage
@updateId = 6

PUT {{url}}/api/carriages/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "New Train 233",
  "trainCompanyId" : 1,
  "status" : ""
}


### 

# @name SoftDeleteCarriage
@deleteId = 1

PATCH {{url}}/api/carriages/{{deleteId}}