@url = https://localhost:5001
@router = api/carriageTypes

### 

# @name addCarriageType
POST {{url}}/api/carriageTypes
Content-Type: application/json

{
  "Name": "New type",
  "ServiceCharge": 123,
  "numberOfCompartments": 2,
  "NumberOfSeats": 32,
  "NumberOfSeatTypes": 2,
  "Status": "Active",
  "Description": "New type description"
}


### 

# @name getListOfCarriageType
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &searchTerm=Pokimane
  # &sort=ageDesc


### 

# @name getListOfCarriageTypeNoPaging
GET {{url}}/{{router}}/all

### 

# @name getCarriageTypeById
@id = 1

GET {{url}}/{{router}}/{{id}}


### 
#  NOTED: NumberOfCompartments: Nghiệp vụ mặc định Compartment dựa theo CarriageType
# @name updateCarriageType
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json
#
{
  "Id": {{updateId}},
  "Name": "New type Update",
  "NumberOfCompartments": 4,
  "ServiceCharge": 222,
  "Status": "Active"
}


### 

# @name softDeleteCarriageType
@deleteId = 2

PATCH {{url}}/{{router}}/{{deleteId}}


### 

# @name addCarriageTypeValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "",
  "ServiceCharge": 0,
  "Status": "",
  "Description": ""
}