@url = https://localhost:5001
@router = api/carriages

### 

# @name addCarriage
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name" : "Test",
  "TrainId" : 1,
  "CarriageTypeId" : 1,
  "NumberOfCompartments" : 2,
  "Status" : "Active"
}


### 

# @name getNumberOfCompartmentsBelongsTo
@idToCount = 2

GET {{url}}/{{router}}/{{idToCount}}/compartments

###

# @name getListOfCarriage

GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=5
  # &searchTerm=New Train
  # &sort=nameDesc
  # &trainCompanyId=2

###

# @name getListOfCarriageNoPaging

GET {{url}}/{{router}}/all


### 

# @name getCarriagenById
@id = 1

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateCarriage
@updateId = 6

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "name": "Updated",
  "trainId": 2,
  "carriageTypeId": 2,
  "NumberOfCompartments": 3,
  "status": "Active"
}


### 

# @name SoftDeleteCarriage
@deleteId = 1

PATCH {{url}}/{{router}}/{{deleteId}}


### 

# @name addCarriageValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name" : "",
  "TrainId" : "1",
  "CarriageTypeId" : "1",
  "NumberOfCompartment" : 1,
  "ServiceCharge" : 0,
  "Status" : "Test"
}