@url = https://localhost:5001
@router = api/compartments

### 

# @name addCompartment
POST {{url}}/{{router}}
Content-Type: application/json

{
  "name" : "Khoang 2",
  "carriageId" : 1,
  "numberOfSeats" : 1,
  "Status" : "Test"
}


### 

# @name getListOfCompartment
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=5
  #&searchTerm=Khoang 1
  #&sort=numberOfSeatsAsc
  #&carriageId=1


### 

# @name getCompartmentById
@id = 3

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateCompartment
@updateId = 3

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id" : {{updateId}},
  "name" : "Khoang 3",
  "carriageId" : 2,
  "numberOfSeats" : 50,
  "Status" : "Da Sua"
}


### 

# @name SoftDeleteCompartment
@deleteId = 3

PATCH {{url}}/{{router}}/{{deleteId}}

###

# @name addCompartmentValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "name" : "test",
  "carriageId" : 1,
  "numberOfSeats" : 1,
  "Status" : ""
}