@url = https://localhost:5001
@router = api/dailycashtransactions

### 

# @name getListDailyCashTransactionNoPagin
GET {{url}}/{{router}}/all


### 

# @name getListDailyCashTransactionByDate
@startDate = 2024-01-29 09:26:43.6596570
@endDate = 2024-01-30 14:35:58.3136400
GET {{url}}/{{router}}/by-date/{{startDate}}/{{endDate}}


### 