@url = https://localhost:5001
@router = api/distancefares

### 

# @name addDistanceFare
POST {{url}}/{{router}}
Content-Type: application/json

{
  "TrainCompanyId": 5,
  "Distance": 1999,
  "Price": 999
}


### 

# @name getListOfDistanceFare
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &sort=trainCompanyNameDesc
  # &trainCompanyId=2
### 

# @name getDistanceFareById
@id = 1

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateDistanceFare
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "TrainCompanyId": 1,
  "Distance": "999999",
  "Price": "999999"
}


### 

# @name SoftDeleteDistanceFare
@deleteId = 10

PATCH {{url}}/{{router}}/{{deleteId}}

### 

# @name addDistanceFareValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "TrainCompanyId": 2,
  "Distance": 2000,
  "Price": 2000
}

###

GET {{url}}/{{router}}/test/500