@url = https://localhost:5001
@router = api/passengers

### 

# @name addPassenger
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "test new nek",
  "CardId": "1234 4321 1234",
  "Age": 18,
  "Gender": "Male",
  "Phone": "123 456 7890",
  "Email": "test@gmail.com"
}


### 

# @name getListOfPassengers
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &searchTerm=Pokimane
  # &sort=ageDesc


### 

# @name getPassengerById
@id = 1

GET {{url}}/{{router}}/{{id}}


### 

# @name updatePassenger
@updateId = 55

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "test update test 1111111test update",
  "CardId": "1234 4321 1234",
  "Age": 22,
  "Gender": "Male",
  "Phone": "123 456 7890",
  "Email": "test@gmail.com"
}


### 

# @name softDeletePassenger
@deleteId = 2

PATCH {{url}}/{{router}}/{{deleteId}}


### 

# @name addPassengerValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "",
  "CardId": "",
  "Age": 0,
  "Gender": "",
  "Phone": "",
  "Email": "asdasd@gmail.com"
}