@url = https://localhost:5001
@router = api/payments

### 

# @name addPayment
POST {{url}}/{{router}}
Content-Type: application/json

{
  "AspNetUserId": "c7a840c8-d3d3-450c-adf6-497dfb75195f",
  "Status": "Okla"
}


### 

# @name getListOfPayment
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=5
  # &searchTerm=New Payment
  #&sort=nameDesc
  # &PaymentCompanyId=2
  # &CreatedAt=""2024-01-11 05:38:41.5659920""


### 

# @name getPaymentById
@id = 2

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdatePayment
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "AspNetUserId": "47cf951d-9a88-4245-9fab-31f65b8086db",
  "Status": "Đã thanh toán"
}


### 

# @name SoftDeletePayment
@deleteId = 1

PATCH {{url}}/{{router}}/{{deleteId}}

### 

# @name addPaymentValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "123",
  "PaymentCompanyId": 0,
  "Status": ""
}