@url = https://localhost:5001

###
POST {{url}}/api/productExample
Content-Type: application/json

{
    "name": "test",
    "description": "123 456",
    "price": 100
}

###
GET {{url}}/api/productExample
