@url = https://localhost:5001
@router = api/roundtrip

### 

# @name addRoundTrip
POST {{url}}/{{router}}
Content-Type: application/json

{
  "TrainCompanyId": 2,
  "Discount": 200
}

### 

# @name getListOfRoundTrips
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &searchTerm= 
  # &sort= discountDesc

###

# @name getRoundTripById
@id = 2

GET {{url}}/{{router}}/{{id}}

  
###

# @name getRoundTripByTrainCompanyId
@trainCompanyId = 7

GET {{url}}/{{router}}/trainCompany/{{trainCompanyId}}

### 

# @name updateRoundTrip
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "TrainCompanyId": 1,
  "Discount": 100
}


### 

# @name softDeleteRoundTrip
@deleteId = 6

PATCH {{url}}/{{router}}/{{deleteId}}
