@url = https://localhost:5001
@router = api/schedules

### 

# @name addSchedule
POST {{url}}/{{router}}
Content-Type: application/json

{
  "name": "MySche",
  "trainId": 1,
  "departureStationId": 2,
  "arrivalStationId": 3,
  "departure_date": "01-05-2024 09:00:00", 
  "arrival_date": "01-05-2024 13:00:00",   
  "departure_time": "01-05-2024 09:00:00",
  "duration": 240,
  "status": "Scheduled"
}


### 

# @name getListOfSchedule
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=5
  #&searchTerm=Khoang 1
  #&sort=numberOfSeatsAsc
  #&carriageId=1


### 


# @name getScheduleById
@id = 1

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateSchedule
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id" : {{updateId}},
  "name" : "Khoang",
  "carriageId" : 2,
  "numberOfSeats" : 50,
  "Status" : "Da Sua"
}


### 

# @name SoftDeleteSchedule
@deleteId = 3

PATCH {{url}}/{{router}}/{{deleteId}}

###

# @name addScheduleValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "name" : "test",
  "carriageId" : 1,
  "numberOfSeats" : 1,
  "Status" : ""
}