@url = https://localhost:5001
@router = api/seatTypes

### 

# @name Create
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "test",
  "ServiceCharge": 18,
  "Status": ""
}

###

# @name GetById
@id = 1
GET {{url}}/{{router}}/{{id}}

###

# @name GetAll
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=2
  # &searchTerm=Standard
  &sort=serviceDesc


### 

# @name Update
@updateId = 1

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "test update",
  "ServiceCharge": 18,
  "Status": ""
}


### 

# @name SoftDelete
@deleteId = 1

PATCH {{url}}/{{router}}/{{deleteId}}


### 

# @name CreateValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "",
  "ServiceCharge": 0,
  "Status": ""
}