@url = https://localhost:5001
@router = api/tickets

### 

# @name addTicket
POST {{url}}/{{router}}
Content-Type: application/json

{
  "PassengerId" : 1 ,
  "TrainId" : 20,
  "DistanceFareId" : 1,
  "CarriageId" : 8,
  "SeatId" : 21,
  "ScheduleId" : 31,
  "PaymentId": 2,
  "Status" : "Active"
}


###

# @name getListOfTickets

GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=5
  # &searchTerm=
  # &sort=nameDesc
  # &trainCompanyId=2


### 

# @name getTicketById
@id = 5

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateTicket
@updateId = 7

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "PassengerId" : 3 ,
  "TrainId" : 1,
  "CarriageId" : 1,
  "DistanceFareId" : 1,
  "SeatId" : 2,
  "ScheduleId" : 1,
  "Status" : "Active"
}

### 

# @name SoftDeleteTicket
@deleteId = 1

PATCH {{url}}/{{router}}/{{deleteId}}


### 