@url = https://localhost:5001

### 

# @name addTrainCompany
POST {{url}}/api/traincompanies
Content-Type: application/json

{
  "Name": "New Train Company"
}


### 

# @name getListOfTrainCompany
GET {{url}}/api/traincompanies?
  &pageNumber=1
  &pageSize=3
  # &searchTerm=New Train
  # &sort=nameDesc


### 

# @name getTrainCompanyById
@id = 1

GET {{url}}/api/traincompanies/{{id}}


### 

# @name UpdateTrainCompany
@updateId = 1

PUT {{url}}/api/traincompanies/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "test update test 1111111"
}


### 

# @name SoftDeleteTrainCompany
@deleteId = 1

PATCH {{url}}/api/traincompanies/{{deleteId}}


### 

# @name addTrainCompanyValidation
POST {{url}}/api/traincompanies
Content-Type: application/json

{
  "Name": ""
}