@url = https://localhost:5001

### 

# @name addTrain
POST {{url}}/api/trains
Content-Type: application/json

{
  "Name": "New Train test",
  "TrainCompanyId": 2,
  "Status": ""
}


### 

# @name getListOfTrain
GET {{url}}/api/trains?
  &pageNumber=1
  &pageSize=5
  # &searchTerm=New Train
  # &sort=nameDesc
  # &trainCompanyId=2


### 

# @name getTrainById
@id = 1

GET {{url}}/api/trains/{{id}}


### 

# @name UpdateTrain
@updateId = 6

PUT {{url}}/api/trains/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "New Train 233",
  "trainCompanyId" : 1,
  "status" : ""
}


### 

# @name SoftDeleteTrain
@deleteId = 1

PATCH {{url}}/api/trains/{{deleteId}}