@url = https://localhost:5001
@route = api/traincompanies

### 

# @name addTrainCompany
POST {{url}}/{{route}}
Content-Type: application/json

{
  "Name": "New Train Company",
  "Status": "Test"
}


### 

# @name getListOfTrainCompany
GET {{url}}/{{route}}?
  &pageNumber=1
  &pageSize=3
  # &searchTerm=New Train
  # &sort=nameDesc


### 



# @name getAllTrainCompany
GET {{url}}/{{route}}/all
### 

# @name getTrainCompanyById
@id = 12

GET {{url}}/{{route}}/{{id}}


### 

# @name UpdateTrainCompany
@updateId = 1

PUT {{url}}/{{route}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "test update test 1111111"
}


### 

# @name SoftDeleteTrainCompany
@deleteId = 1

PATCH {{url}}/{{route}}/{{deleteId}}


### 

# @name addTrainCompanyValidation
POST {{url}}/{{route}}
Content-Type: application/json

{
  "Name": ""
}