@url = https://localhost:5001
@router = api/trains

### 

# @name addTrain
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "New Train test",
  "TrainCompanyId": 1,
  "Status": ""
}

### 

# @name getListOfTrain
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &searchTerm=New Train
  #&sort=nameDesc
  # &trainCompanyId=2

### 

# @name getListOfTrainNoPaging
GET {{url}}/{{router}}/all

### 

# @name getTrainById
@id = 3

GET {{url}}/{{router}}/{{id}}


### 

# @name UpdateTrain
@updateId = 6

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "New Train 233",
  "trainCompanyId" : 1,
  "status" : ""
}


### 

# @name SoftDeleteTrain
@deleteId = 1

PATCH {{url}}/{{router}}/{{deleteId}}

### 

# @name addTrainValidation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": "123",
  "TrainCompanyId": 0,
  "Status": ""
}