@url = https://localhost:5001
@router = api/trainstation

### 

# @name addTrainStation
POST {{url}}/{{router}}
Content-Type: application/json

{
  "Name": " 0 Station 2",
  "Address": "123 HN",
  "CoordinateValue": 10,
  "Status": "Active"
}

### 

# @name getListOfTrainStations
GET {{url}}/{{router}}?
  &pageNumber=1
  &pageSize=10
  # &searchTerm= 2
  &sort=coordinateValueDesc


### 

# @name getListOfTrainStationsNoPaging
GET {{url}}/{{router}}/all

### 

# @name getTrainStationById
@id = 1

GET {{url}}/{{router}}/{{id}}

### 

# @name updateTrainStation
@updateId = 2

PUT {{url}}/{{router}}/{{updateId}}
Content-Type: application/json

{
  "Id": {{updateId}},
  "Name": "Station 2",
  "Address": "123 HN",
  "CoordinateValue": 20,
  "Status": "Active"
}