@url = https://localhost:5001
@router = api/users


### 

# @name getListUsers

GET {{url}}/{{router}}

### 


# @name getUserByEmail
@email = nhokpio95@gmail.com

GET {{url}}/{{router}}/{{email}}

### 

# @name getUserById
@idToFind = b9bef31e-47d4-4b85-a926-53e3d6663338

GET {{url}}/{{router}}/get-user-by-id/{{idToFind}}

###

# @name lockUserById
@lockId = b9bef31e-47d4-4b85-a926-53e3d6663338

PUT {{url}}/{{router}}/lock-user/{{lockId}}

###

# @name unlockUserById
@unlockId = b9bef31e-47d4-4b85-a926-53e3d6663338

PUT {{url}}/{{router}}/unlock-user/{{unlockId}}

###

# @name getApplicationRoles
GET {{url}}/{{router}}/get-application-roles


### 

# @name addOrEditUser
POST {{url}}/{{router}}/add-edit-user
Content-Type: application/json

{
    "id": "",
    "username": "1",
    "firstName": "1",
    "lastName": "1",
    "password": "1",
    "roles": "1"
}