global using Application.Common.Exceptions;
global using Application.Common.Interfaces.Services;
global using Application.Common.Models;
global using Application.Common.Models.Pagination;
global using Application.Common.Models.QueryParams;
global using Domain.Entities;
global using Microsoft.AspNetCore.Mvc;
global using WebApi.Exceptions;
global using WebApi.Extensions;